### ISSUE TITLE
Add missing Assertion API

### ISSUE THREAD

**Issue by s1hofmann** [sakuli/sakuli#142]
**Version**
2.0.1

**Short overview**
As a user I want to use assertions as known from Sakuli 1.

**Detailed error description**
Full list of available assertions:

- _assert
- _assertTrue
- _assertNotTrue
- _assertFalse
- _assertNull
- _assertNotNull
- _assertExists
- _assertVisible
- _assertNotVisible
- _assertNotExists
- _assertEqual
- _assertEqualArrays
- _assertNotEqual
- _assertContainsText
- _assertNotContainsText
- _assertEqualImages
- _assertHorizontallyAligned
- _assertVerticallyAligned
- _assertCentered
- _assertVisiblyInside
- _assertVisiblyOutside
- _assertVisiblyOn
- _assertFitsWidth
- _assertFitsHeight

**Comment by tnobody** [comment]
I think we can omit 
- _assertEqualImages
- _assertHorizontallyAligned
- _assertVerticallyAligned
- _assertCentered
- _assertVisiblyInside
- _assertVisiblyOutside
- _assertVisiblyOn
- _assertFitsWidth
- _assertFitsHeight
- _assertNotVisible
- _ assertVisible

Because they are not available in Sahi OS Version.

**Comment by s1hofmann** [comment]
Agreed, didn't consider this fact when compiling the list :+1:

**Comment by svettwer** [comment]
Okay, so we are talking about this list:

- _assert
- _assertContainsText
- _assertEqual
- _assertEqualArrays
- _assertExists
- _assertFalse
- _assertNotContainsText
- _assertNotEqual
- _assertNotExists
- _assertNotNull
- _assertNotTrue
- _assertNull
- _assertTrue

:+1:
