### ISSUE TITLE
Finished state OK even with click error

### ISSUE THREAD

**Issue by ZNicoZ** [sakuli/sakuli#149]
**Short summary**
Is this behavior intended?
Running this code in Sakuli 2.1.0 logs an error but the terminal output logs "everything is fine"
```
(async () => { 
    const testCase = new TestCase();
    try {
        await _navigateTo("https://sakuli.io");              // 1
        await _click(_div("ThisDivDoesNotExist"));
    } catch (e) {
        testCase.handleException(e);
    } finally {
        testCase.saveResult();
    }

})().then(done);
```
**Detailed question**
![image](https://user-images.githubusercontent.com/7655980/60823193-4de56380-a1a7-11e9-8f70-65a67a14fc31.png)

**Comment by tnobody** [comment]
Hi @ZNicoZ,

thanks or your contribution. Can you please try to add an `await` before `testCase.handleException(e)` and `testCase.saveResults()`

**Comment by ZNicoZ** [comment]
Thanks, that does the trick. Is it necessary to put an await before `testCase.endOfStep()` as well?
As the getting started guide on sakuli.io shows:
![image](https://user-images.githubusercontent.com/7655980/60878527-2abac280-a240-11e9-912d-d75481523e4d.png)

**Comment by tnobody** [comment]
Nice :)

No since `endOfStep` is just a sync function. 
We already have an branch for typescript integration: https://github.com/sakuli/sakuli/tree/feature/ts-support
With this feature your IDE will be abel to detect missing awaits where it's necessary

**Comment by sni** [comment]
wouldn't it be better if all those awaits won't be neccessary at all? What if ex.: _navigateTo is just a wrapper for a async _navigateToAsync?
To me, all these awaits are error prone, ugly and not neccessary at all. If there is any usecase to have async test cases, then you could use the async variant of these functions.

**Comment by tnobody** [comment]
Hi @sni,

thank for for your recommendation. I see your point with this syntax but _unfortunately_ it's not that easy to accomplish such a change. There are some issues which I want to briefly point out:

- It's not (natively) possible to wrap async code into blocking code in JavaScript. There are projects like [Node Fibers](https://www.npmjs.com/package/fibers) but they are relying on OS specifics AFAIK. TBH I didn't spend to much time investigating this package and all possible implications of using Fibers
- The underlaying Frameworks (selenium and nut.js) are mainly promise based and async by it's nature and implementation, so it is hard to escape from this (since wrapping to blocking methods/functions is not suitable)
-  async/await is the most idiomatic approach in modern JavaScript

One little remark at the end: It is kinda funny to see that people which are (supposedly) not that close to the JavaScript world have this opinion on async/await, because for the most JavaScript developers this syntax was/is the best thing since some monks brewed the first beers ([escaping the callback-hell](https://blog.hellojs.org/asynchronous-javascript-from-callback-hell-to-async-and-await-9b9ceb63c8e8)) ;)

In the future we will provide tools that will help you handling async code (like typescripts build-in hints on unused/unawaited promises)
