### ISSUE TITLE
Pure native testing without launching browser

### ISSUE THREAD

**Issue by rahulmr** [sakuli/sakuli#171]
**Short overview**
Pure native testing without launching browser

**Use case**
I have some native windows applications which I want to automate using sakuli.
This application is not supported by many commercial software so we need to use image based automation.
Also, tesseract and open cv based sikuli currently.
There is no need to launch browser all the time.

**Detailed feature description**
Provide pure native app testing when browser is kept as none.
So if `testsuite.properties` contains `testsuite.browser=none` no browser should be launched

**Additional content**
> Please provide any (mandatory) additional data for your desired feature

**Comment by tnobody** [comment]
@s1hofmann what do you think should be the default behavior when calling a sahi functions without a browser:

1. Throwing an Error "_navigateTo is not defined" --> Just not inject any Sahi Function to the context
2. Throwing an Error "_navigateTo cannot be invoked when no browser is started"
3. Logging a warning "_navigateTo does nothing when no browser is started" 

2. and 3. would require to inject a dummy implementation of the sahi api

**Comment by s1hofmann** [comment]
I would prefer option 2.

I think throwing an error when trying to invoke Sahi API functions is the most "obvious" solution.
A `$functionName is not defined` error might be misleading at first, a dedicated error message would be preferable.
On the other hand, just logging the error seems even more confusing to me, since it would look like the test is running fine, but nothing happens. One only realises the error after checking the log file.

**Comment by rahulmr** [comment]
@s1hofmann is the documentation updated for the same? Any link? So, it is that I need to use browser=none in the properties file or is there any other way to do so?

**Comment by s1hofmann** [comment]
Hi @rahulmr, we're not yet finished with updating our docs, but to enable ui-only tests you would've to set `testsuite.uiOnly=true` in your `testsuite.properties`.

**Comment by rahulmr** [comment]
Thanks @s1hofmann
