### ISSUE TITLE
Sakuli 1 variables in Sakuli 2 are not accessible

### ISSUE THREAD

**Issue by WWIJP** [sakuli/sakuli#207]
**Version**
Sakuli 2

**Short overview**
Sakuli 1 variables has to be accessible as well in Sakuli 2

**Detailed error description**
Variables are not usable

**Steps to reproduce error**
Variables are not usable

**Additional content**
variables of: sakuli.properties and testsuit.properties
Sakuli 1 docu: https://consol.github.io/sakuli/latest/index.html#property-loading-mechanism

> Please provide any (mandatory) additional data to reproduce the error (Code, Config, Dockerfiles etc.)

**Comment by WWIJP** [comment]
Currently needed variables: 
sakuli.autoHighlight.enabled=false
sakuli.highlight.seconds=1.1f

sakuli.screenshot.onError=true
sakuli.screenshot.format=png/jpg
sakuli.screenshot.dir=${sakuli.log.folder}/_screenshots

sakuli.environment.similarity.default=0.99

log.level.sakuli=WARN/CRIT/UNKNON/OK
sakuli.log.folder=${sakuli.testsuite.folder}/_logs


ext.http.proxy.enable=true
ext.http.proxy.host=
ext.http.proxy.port=
ext.http.proxy.auth.enable=
ext.http.proxy.auth.name=
ext.http.proxy.auth.password=

ext.https.proxy.enable=
ext.https.proxy.host=
ext.https.proxy.port=
ext.https.proxy.auth.enable=
ext.https.proxy.auth.name=
ext.https.proxy.auth.password=

sakuli.forwarder.check_mk.enabled=true
sakuli.forwarder.check_mk.spooldir=/var/lib/check_mk_agent/spool
sakuli.forwarder.check_mk.freshness=900

testsuite.id=
sakuli.forwarder.check_mk.spoolfile_prefix=
sakuli.forwarder.check_mk.service_description=
sakuli.forwarder.json.enabled=false

etc.

**Comment by tnobody** [comment]
Hallo @WWIJP,

thank you for your contribution. Can you explain what do you exactly mean with `not usable` since every property may effect other aspects of Sakuli?

Basically you can still use the files `testsuite.properties` and `sakuli.properties` as in Sakuli v1. 
Not all of them will take effect rightnow (for different reasons) but the most of them should still work. I'll explain in detail based on your list:

## Highlighting

```properties
sakuli.autoHighlight.enabled=false
sakuli.highlight.seconds=1.1f
```
This property belonged to the `Region` class in Sakuli v1 and enabled autohighlighting any new Region. The duration (`sakuli.highlight.seconds`) only applies to this "auto-highlights". Since native screen highlighting is not yet implemented, this property doesn't has any effect so far. Status of native highlight is documented in: https://github.com/sakuli/sakuli/issues/167

## Screenshots

```properties 
sakuli.screenshot.onError=true
sakuli.screenshot.format=png/jpg
sakuli.screenshot.dir=${sakuli.log.folder}/_screenshots
````

The screenshot dir will be configurable with the next release: https://github.com/sakuli/sakuli/issues/205. The `onError` property has no effect so far, if it is required please open a new dedicated issue. The format of the screenshot is set to `.png` and we are not planning to make this configurable (but you can still open an issue if there is a usecase)

## Similarity

```properties
sakuli.environment.similarity.default=0.99
```

This property has no more effect since we use more clever algorithm to match a screenshot with the current screen content. Maybe @s1hofmann can provide more insights on this :)

## Log Configuration

```properties
log.level.sakuli=WARN/CRIT/UNKNON/OK
sakuli.log.folder=${sakuli.testsuite.folder}/_logs
```

This properties will take effect in an upcoming release and are already issued in  
https://github.com/sakuli/sakuli/issues/201 and https://github.com/sakuli/sakuli/issues/205

## Proxy settings

```properties
ext.http.proxy.enable=true
ext.http.proxy.host=
ext.http.proxy.port=
ext.http.proxy.auth.enable=
ext.http.proxy.auth.name=
ext.http.proxy.auth.password=

ext.https.proxy.enable=
ext.https.proxy.host=
ext.https.proxy.port=
ext.https.proxy.auth.enable=
ext.https.proxy.auth.name=
ext.https.proxy.auth.password=
```

This proxy settings where used by the internal proxy from sahi in Sakuli v1. Since Sakuli v2+ doesn't use such a technology it is not longer needed to configure a proxy in Sakuli itself. The proxy have to be configured the machine (your computer, a container, a virtual machine, etc) where sakuli is executed. If you encounter any special issues with sakuli behind a proxy feel free to [open](https://github.com/sakuli/sakuli/issues/new/choose) a dedicated issue.

## Check_MK Forwarder

```properties
> sakuli.forwarder.check_mk.enabled=true
> sakuli.forwarder.check_mk.spooldir=/var/lib/check_mk_agent/spool
> sakuli.forwarder.check_mk.freshness=900
> sakuli.forwarder.check_mk.spoolfile_prefix=
> sakuli.forwarder.check_mk.service_description=
``` 

This options are available with an [enterprise subscription](https://sakuli.io/enterprise/). Please make sure you have the forwarder addon correctly [installed and configured](https://sakuli.io/docs/enterprise/check_mk-forwarder/). 

## Testsuite ID

```properties
testsuite.id=
```

This should work as expected (when configured in `testsuite.properties`). If you encounter any bugs or unexpected behavior open a [new issue](https://github.com/sakuli/sakuli/issues/new/choose)

## JSON Forwarder

```properties
sakuli.forwarder.json.enabled=false
```

JSON Forwarding is currently not support but considered as an Enterprise Addon in the future.

Br
