### ISSUE TITLE
Debrecated Code

### ISSUE THREAD

**Issue by WWIJP** [sakuli/sakuli#209]
**Version**
Sakuli 2.1.2

**Short overview**
We getting the mesages about debrecated code:
(node:76257) [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
(node:76257) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:76257) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
(node:76257) ExperimentalWarning: The fs.promises API is experimental

**Detailed error description**
We getting the mesages about debrecated code:
(node:76257) [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
(node:76257) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:76257) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
(node:76257) ExperimentalWarning: The fs.promises API is experimental

**Steps to reproduce error**
Starting a testcase.js

**Additional content**

**Comment by tnobody** [comment]
Hello @WWIJP,

thank you for your contribution. Unfortunately this are platform dependent warnings, they are ok but will print "unnecessary" output to the CLI.

You can avoid this messages by setting the environment variable `NODE_NO_WARNINGS` to `1`.

We created an Issue to add this to the Sakuli documentation: https://github.com/sakuli/sakuli.github.io/issues/84

Since there is no possibility to fix this within Sakuli I'll close this issue.

Br
