### ISSUE TITLE
Save error page as html file

### ISSUE THREAD

**Issue by WWIJP** [sakuli/sakuli#215]
**Short overview and use case**
It would be good to have the possibility to save the current page, which causes an error, to save as html file. 
Later it is possible to analyse the html file and the code to enhance the test case for such problems.
A possiblity would be a script entry like "env.saveHTML("<$path/$date_$filename.html>")".

**Comment by s1hofmann** [comment]
When it comes to debugging a failing Sakuli check static HTML is only partially helpful for root cause analysis.
While it allows to identify simple errors like changed / wrong identifiers, it is not possible to analyse errors caused by dynamic components like animations, transitions or dynamically loaded content (which might not have been available at the very moment).
Saving HTML content might also expose sensitive data to anyone with access to the filesystem.

**Comment by svettwer** [comment]
closed due to inactivity
