### ISSUE TITLE
New Sakuli DSL

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#244]
As a test developer, I want to use a more convenient DSL in a less complex project setup, to improve productivity.

**Comment by tnobody** [comment]
As discussed today I would suggest to spilt our DSL definition into two parts:

- TestRunner DSL
- Testing DSL

With this distinction we are able to address different pain points better and are able to move sakuli to a DSL step-by-step:

Here is a brief overview:

## TestRunner DSL

You can roughly think about Testrunner DSL as the boilerplate-code of metadata which describes your Test and teststeps but not your expectations or concrete actions. An example for a TestRunner-DSL is `jest`s and/or `jasmine`s BDD-style approach:

```typescript
describe('a system under test', () => {
  it('should behave as expected', async () => {
    // here is the actual testing DSL
  })
}) 
``` 

Or from another language like Java: 
```java

@SpringBootTest()
class SystemUnderTestTest {

  @Test
  public shouldBehaveAsExpectedTest() {
      // here is the actual testing DSL
  }
}

```

Important is that a new approach should be opt-in and compatible with `@sakuli/legacy-dsl`. So that a user can use the new TestRunner DSL while still using Testing-DSL functions like `_click(...)`,  `scree.find(...)` and so on.

Doing something like: 
```typescript
describe('a sakuli test', () => {
  const tc = new TestCase();
})
```

Will eventually fail since Sakulis TestExecutionContext doesnt allow to start a new TestCase while another  one is running.

IMHO the Testrunner should address the following pain points:

- Reduce/Remove of boilerplate files (testsuite.suite, testsuite.properties)
- Remove strict folder structure
- Provide a declarative way to describe a testcase
  - Remove `.endOfStep` after a step 

To accomplish this goals I would suggest to spilt the TestRunnerDsl into two (idependent) aspects:

- TestCase detecting by filepattern (with carefully considered defaults) to remove filesystem boilerplate
- New DSL-Methods to execute a testcase (e.g. `describe`, `it` and so on)

Both have to be compatible with existing `@sakuli/legacy-dsl` but should be easily used as an opt in.

## Testing DSL

A Testing DSL is the actual code that interacts with the Browser and Environment. 
Examples for Testing DSLs:
- [taiko](https://taiko.gauge.org/?utm_source=how_taiko_blog&utm=medium=blog&utm_campaign=taiko_blogpost&utm_term=&utm_content=#smart-selectors)
- [selenium](https://www.npmjs.com/package/selenium-webdriver)
- [puppeteer](https://github.com/GoogleChrome/puppeteer)
