### ISSUE TITLE
Fetch Retry Performance

### ISSUE THREAD

**Issue by ZNicoZ** [sakuli/sakuli#251]
We should find a way to reduce the duration Sakuli tries to find an element that does not exist. If we don´t find a generic way to solve this, we should let the user choose a threshold for each fetch.

Solutions should be discussed here.

**Comment by tnobody** [comment]
The problem here is the current implementation:

Sakuli fetches dom elements by an [query](https://sakuli.io/apidoc/sakuli-legacy/interfaces/sahielementquery.html) which contains information to find an element in dom - lets call that mechanism resolving. Sakuli does two things to "really make sure an element exists or not":

1. Sakuli resolves the query with at most ten retries until no error is thrown
2. Point 1. is wrapped in a [WebDriver.wait](https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/index_exports_ThenableWebDriver.html#wait) with an timeout of 10s. `wait` will execute a callback either until it not fails or the given timeout is exceeded. Since promises can't be cancelled it will eventually execute the latest scheduled execution of the callback within the timeout - even if timeout i exceeded during this execution.

That is... let's say... a not very suitable implementation so far because we have an implicit retry mechanism (through the `WebDriver.wait()`) and an explicit retry mechanism within each retry scheduled by `WebDriver.wait`... which is kind of senseless and way to hard to handle, debug, etc.

In regard to #221 we can observe another inconvenient behavior: 
In a situation where Sakuli tries to fetch a `<div>` on a page with ~1500 divs the basic resolving will take ~8.5s (interpolated numbers from https://github.com/sakuli/sakuli/issues/221#issuecomment-532223748). When the element does not exists the fetch will fail within the timeout of 10s an wait invokes the callback (which resolves the query) another time and wait until it fails again for another 8.5s. only then it will check that the time is exceeded, but the total time of the operation took 17s (8.5s*2).

IMHO we can have quick wins by just decreasing the implicit wait timeout in FetchUtils.fetchElements.
And remove the explicit retry mechanism in fetch elements at all.
Removing the explicit retry will help to avoid extrem exceeding of timeouts because the callback in `WebDriver.wait` fails faster.

I would propose a timeout of maximum 2 seconds.

If an element takes longer to by "fetchable" but the tester is sure that it will appear than an explicit wait could be a good workaround:

```typescript
await _wait(5000, () => _isVisible(_link("I will be late but I will be there"))); // waiting at most 5s for the element
```

Better handling for dynamic waits are discussed in #115 

Additionally we can discuss if the user might set the fetch timeout via the API. I see tow approaches here:
- Introduce a global function like `_setFetchTimeout(5000)` or `env.setFetchtimeout(5000)`
- Introduce an optional parameter (at the end of paramter list) on every function that will fetch an element e.g. `await _click(_link('Home'), 5000)` 

The first approach is closer to the patterns in Sahi and Sakuli API but might be hard to handle since we have to implicitly set a global state.

Second approach can be inconvenient for functions that already have optional parameters since the user is then required to set both paramter (AFAICS only [`_getOptions`](https://sakuli.io/apidoc/sakuli-legacy/interfaces/fetchapi.html#_getoptions) will be affected from this.

**Comment by tnobody** [comment]
After discussion we will go for Introduce a global function like _setFetchTimeout(5000) or env.setFetchtimeout(5000)
