### ISSUE TITLE
_in searches the first identical webelement

### ISSUE THREAD

**Issue by cliffle** [sakuli/sakuli#261]
**Version**
2.1.3

**Short overview**
`_in()` will always search in the first webelement if there are multiple identical webelements.

**Detailed error description**
Below is an example of such behaviour. Instead of looking in the parent node, Sakuli searches in the first webelement, which is identical to `parent`. As a test developer I expect, that `const price` should be `400€ per month` and not `Free Open Source`.

**Steps to reproduce error**
```javascript
(async () => {
    const tc = new TestCase();
    try {
        await _navigateTo("https://sakuli.io/enterprise/");

        const parent = await _parentNode(_div(/400/), "li", 1);
        await _highlight(parent);
        const price = await _getText(_div("price"), _in(parent));
        await tc.endOfStep(price);
    } catch (e) {
        await tc.handleException(e);
    } finally {
        await tc.saveResult();
    }
})().then(done);
```

**Comment by svettwer** [comment]
Analysis required first.

**Comment by tnobody** [comment]
Hi,

I did some analyses and in this particular case the error not the behavior of Sakuli rather than a bug in the test itself.

```diff
(async () => {
    const tc = new TestCase();
    try {
        await _navigateTo("https://sakuli.io/enterprise/");

        const parent = await _parentNode(_div(/400/), "li", 1);
        await _highlight(parent);
-       const price = await _getText(_div("price"), _in(parent));
+       const price = await _getText(_div("price", _in(parent)));
        await tc.endOfStep(price);
    } catch (e) {
        await tc.handleException(e);
    } finally {
        await tc.saveResult();
    }
})().then(done);
```

The `_in` relation is not the second parameter of the `_getText` function. When you move it to be the second parameter of the query `_div('price', _in(parent))` than the behavior is as you expect it.

Btw. when you run the test with typescript the compiler will inform you about this ;)

```bash
Error: /Users/timkeiner/Projects/consol/TA/sakuli_v2/packages/integration-tests/legacy-suite/test-case/typed-case.ts(9,53): semantic error TS2554 Expected 1 arguments, but got 2.
```

@cliffle do you have another example where the behavior of `_in` is not as expected? Otherwise, I would close this ticket.

**Comment by cliffle** [comment]
Hi @tnobody,

thank you for your response. I just checked the other test cases, where I used the `_in` relation and when I used it as you described, it works as expected. I am closing this ticket because this resolves my problem.
