### ISSUE TITLE
Missing await statement causes missing forwarding

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#308]
As a Sakuli user, I want Sakuli to forward my test results even if I forget `await` statements in the test code, so that Sakuli is more bulletproof.

During the analysis of sakuli/todo#49 - where a `testCase.endOfStep` seems to cause a missing forwarding - we found out that the issue is caused by a missing `await` on a `env.Type` statement. After some research we came up with the theory that the missing `await` and the resulting unresolved promise might have blocked the call stack so that the `END_EXECUTION` event which triggers the forwarders forwarding logic might not be recognized by the context in time, before all forwarder promises are resolved and the tear down of the forwarder occurs. The issue here is, that the shutdown of the context (including forwarder promise resolving and tear down) is not depending on the `END_EXECUTION` event but on the regular code flow.

Therefore we should ensure that the forwarder promise resolving and tear down depends on the `END_EXECUTION` event and the successful registration of all tasks to be executed based on this event.

**Comment by tnobody** [comment]
After `runner.execute` we could a promise that resolves when the `END_EXECUTION` event is triggered. We should await this promise to resolve before the forwarder teardown is invoked and, therefore, the forwarding queue is purged. 

We have to keep the following things in mind for the registration of the listener:
- Since `runner.execute` will eventually fire the `END_EXECUTION` event, we have to register the listener for the "blocking promise" before invoking `runner.execute` otherwise, the listener will never be invoked
- the listener should be registered right after the forwarder listeners are registered to ensure that the "blocking promise" will resolve after all other listeners are handled (which means that the forwarding methods were invoked)

**Comment by svettwer** [comment]
should not occur anymore due to `exit` to `exitCode` change
