### ISSUE TITLE
Clickable element covered from cookie banner after scroll into view is not clickable.

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#332]
As a Sakuli user, I want sakuli to throw an exception in case an element is not clickable because it is hovered by an overlay e.g. Cookie banners, so that my test does not continue because of a false positive click action.

**Additional information**
Currently when a covered element is clicked, the click is logged as successful by Sakuli but the webpage does not change its content nor redirects.

**Tests to reproduce**
```javascript
(async () => {
    const testCase = new TestCase();
    try {
        await _navigateTo("https://sakuli.io");
        await _click(_link("Legal Notice"));
        await _assertNotExists(_heading1("Legal Notice"));
    } catch (e) {
        await testCase.handleException(e);
    } finally {
        await testCase.saveResult();
    }
})();
```

**Acceptance criteria**:
- [ ] The upper test case fails because `_click(_link("Legal Notice"))` cannot be clicked.

**Workaround**
Closing the cookie banner will make the test pass.

**Comment by ZNicoZ** [comment]
Just some thoughts:

"As a Sakuli user, I want sakuli to successfully click elements covered from an overlay element e.g. cookie banners, so that my test continues as expected."

When we think about simulating users with Sakuli, this would not be consistent. The click should fail as the element is not visible (in this case covered by an overlay).
I´m not sure if this is even possible to identfy something like that and react accordingly? 
We also have to think about text fields that sometimes have overlays that disappear after a click on the input field, releasing the actual input field and setting the focus/curser. This should of course be possible.

Another thought is this: as I recollect, scroll-into-view tries to scroll an element into the middle of the screen, we should investigate why this does not happen here. Of course it doesn´t work with an element that is at the bottom of a page already.

- identifying overlays and adjust scroll into view accordingly 
- if an element is not visible / in the viewport / hidden by an overlay, and Sakuli is able to click it anyways but nothing is triggered by this action, the test should also fail

Let´s discuss this in person and the team

**Comment by tnobody** [comment]
I agree with @ZNicoZ that Sakuli testcases should reflect the required user behavior as close as possible. If a user has to do an extra click to remove an overlay than this has to be reflected in a sakuli test as well (i would agree that Sakuli might add more _magic_ when we talk about RPA-scenarios).

IMHO the real problem here is that the "click" seams to work since it does not throw any exception... I can remember that selenium usually throws an exception if a click target is not clickable (e.g. it is behind an overlay). Maybe it has something to do with the circumstance that a Sakuli click doesn't  use `WebElement.click()` rather than creating and performing an action-sequence instead (this is because `WebElement.click()` doesn't provide a possibility to click something with combination keys like <kbd>CTRL</kbd>). I can imagine that the action-sequence is somehow more tolerant or doesn't check if a click actually triggers a click event at that particular element. So the person who assigns to that ticket might investigate in that direction also.

And as @ZNicoZ already said, the second Acc. Crit. cannot be fulfilled with the provided testcase since the link is at the bottom of the page. Sakuli uses native [`scrollIntoView`](https://developer.mozilla.org/de/docs/Web/API/Element/scrollIntoView) which is invoked on the element directly in the browser. It already passes options to scroll that element into the center of the viewport.

**Comment by svettwer** [comment]
acceptance criteria updated!
