### ISSUE TITLE
Preset provider not loaded when using npx sakuli run

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#333]
As a Sakuli user, I want Sakuli to recognize my preset provider for e.g. monitoring forwarding, when I start Sakuli via `npx sakuli run /path/to/testsuite/legacy-suite`.

**Additional information**
Project structure is:
```
$ tree .
.
├── legacy-suite
│   ├── sakuli.log
│   ├── test-case
│   │   └── case.js
│   ├── testsuite.properties
│   └── testsuite.suite
├── package.json
└── sakuli.log

```
Command is `npx sakuli run legacy-suite`

I assume the reason for Sakuli not using the preset providers is that they are defined in the package.json and not in the testcase itself. 

**Acceptance criteria**
- [ ] The preset provider are loaded on `npx sakuli run legacy-suite`

**Workaround**
`npm --prefix /path/to/testsuite/ test`
This will use the defined `test` script of the package json and therefore load the preset provider.

**Comment by svettwer** [comment]
Review due to auto discovery feature

**Comment by cliffle** [comment]
Just tested this with version `2.3.1-next.262` and I'm getting the following output when running `npx sakuli run sakuli_test/sakuli_test_suite/`:
```
node_modules found: /home/cliff/.nvm/versions/node/v12.16.2/lib/node_modules
No Sakuli presets found during auto discovery
Could not get preset information from '/tmp/package.json', because: Error: ENOENT: no such file or directory, open '/tmp/package.json'
No sakuli preset configuration in package.json found
```
The issue is that we try to get the package.json with https://github.com/sakuli/sakuli/blob/13a993ea45d1501a00218c2336649996eceec404/packages/sakuli-core/src/bootstrap/load-bootstrap-options.function.ts#L29

Instead of `cwd()` we need the sakuli project path.
One approach might be to get the parameters of the sakuli run command with `yargs.argv._` in `sakuli-cli/index.ts` as this is the only place where `loadBootstrap()` is called. From this, we can determine the sakuli project path.

**Comment by svettwer** [comment]
I am not able to reconstruct the issue anymore. Nevertheless, the upper analysis revealed a different issue. If you execute Sakuli from somewhere on a system by using a global Sakuli installation, Sakuli won't start because it is unable to find the package.json in the current working directory. I'll create a different Issue for this.
