### ISSUE TITLE
Error messages from test failures are not propagated to CLI

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#353]
As a Sakuli user, I want to receive the detailed error message in case a test case failed instead of the currently displayed generic message.

**Additional information**
When an error occurs during test execution a generic error message is shown which seems to be thrown from the retry mechanism compensating stale element reference errors.
```
Error: A non StaleElementReferenceError is thrown during retrying;
TimeoutError: Cannot find Element within 3000ms by query:
Locator: By(css selector, a)
identifier: Legal Notice
relations:
Wait timed out after 3481ms
```

This is also the case even if the root cause if different (e.g. element is not visible/covered by another element)

**Acceptance criteria**
- [ ] Improve the error message display so that the root cause of the test failure is transparent to the user

**Comment by s1hofmann** [comment]
Root cause:

- `runAsAction` uses `withTryAcrossFrames`
- `withTryAcrossFrames` only keeps the last exception
- In case of an frame / iframe available on a page, non-existent elements within the frame will cause an element not found exception, which gets propagated and shadows the initial root cause

Solution:

- WIP
