### ISSUE TITLE
Sakuli should gracefully exit on SIGINT and SIGTERM

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#424]
As a user, I want Sakuli to exit gracefully when SIGINT, SIGTERM or SIGKILL is send, to be able to abort test/check execution instantaneously.

Acceptance criteria:
- [x] SIGINT, SIGTERM and ~SIGKILL~ are caught and cause a graceful shutdown of the test execution
- [x] browser windows and other opened application are closed
- [x] A test/check abortion via SIGINT/SIGTERM/SIGKILL is mentioned in the logs
- [x] The return value of Sakuli in case of SIGINT/SIGTERM/SIGKILL is 130 (according to bash docs)
- [x] Registered forwarder executions are prohibited

**Comment by s1hofmann** [comment]
Some findings:

- [It's not possible to attach a listener to `SIGKILL`](https://nodejs.org/api/process.html#process_signal_events), process will be killed unconditionally
- Windows seems to behave a bit differently since it does not support signals

**Comment by s1hofmann** [comment]
Related issues:

- #260

**Comment by s1hofmann** [comment]
In my recent tests I noticed strange behaviour when cancelling a test execution. Even though script execution is configured to break on `SIGINT`, exceptions are thrown stating the webdriver instance is no longer available. 

This is a bit weird, since the webdriver instance seems to get terminated, but the script execution still continues to run (at least for a bit).
I'd love to investigate this issue in a pair programming session.
