### ISSUE TITLE
sakuli.forwarder.icinga2.output.details analog/like checkmk

### ISSUE THREAD

**Issue by aendieh** [sakuli/sakuli#515]
**Short overview**
Add a property to disable/modify the html output of sakuli2 to icinga2 forwarder. 

**Use case**
Complex E2E Checks output will be confusing. We are testing this in one scenario and the icinga-output is huge.
To simplify readablity and usability for the teams being alerted, this would help out greatly.

**Detailed description**
I propose a property for:
true: full output
false: no output
steps: only show major steps, defined in the suite (like Sakuli1)
warn: only show warning and critical
crit: only show critical

**Additional content**
none needed

> Please provide any (mandatory) additional data for your enhancement
none needed

**Comment by svettwer** [comment]
Hi! :wave: 

Thank you for reaching out. We'll take your proposal into consideration. As the forwarder are part of Sakuli enterprise features and not available as open source, I'll move this issue into the corresponding repository. Since we'd like to obtain some more information about the actual problem of huge icinga-output and your priority on this topic, please contact our enterprise support at the address known to you.

BR,
Sven

**Comment by svettwer** [comment]
Closed in favor of https://github.com/sakuli/sakuli-enterprise-forwarder/issues/78
